# Generated by Django 3.2.3 on 2021-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
