# Generated by Django 3.2.3 on 2021-07-20 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210719_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE PUBLISHED'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TITLE'),
        ),
    ]
