# Generated by Django 3.1.6 on 2021-08-07 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=60)),
                ('Jan', models.CharField(max_length=200, verbose_name='Jan')),
                ('Feb', models.CharField(max_length=200, verbose_name='feb')),
                ('Mar', models.CharField(max_length=200, verbose_name='May')),
                ('Apr', models.CharField(max_length=200, verbose_name='Apr')),
                ('May', models.CharField(max_length=200, verbose_name='May')),
                ('Jun', models.CharField(max_length=200, verbose_name='Jun')),
                ('Jul', models.CharField(max_length=200, verbose_name='Jul')),
                ('Aug', models.CharField(max_length=200, verbose_name='Aug')),
                ('Sep', models.CharField(max_length=200, verbose_name='Sep')),
                ('Oct', models.CharField(max_length=200, verbose_name='Oct')),
                ('Nov', models.CharField(max_length=200, verbose_name='Nov')),
                ('Dec', models.CharField(max_length=200, verbose_name='Dec')),
            ],
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('-mod_date',), 'verbose_name': 'community', 'verbose_name_plural': 'communitys'},
        ),
        migrations.AddField(
            model_name='community',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='community',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AlterField(
            model_name='community',
            name='body',
            field=models.TextField(default='', verbose_name='CONTENT'),
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE PUBLISHED'),
        ),
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TITLE'),
        ),
        migrations.AlterModelTable(
            name='community',
            table='community_posts',
        ),
    ]
