# Generated by Django 3.2.3 on 2021-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210720_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='author',
            field=models.CharField(default='', max_length=10),
        ),
    ]
