# Generated by Django 3.2.3 on 2021-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_community_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
    ]
